name: Compile & release definitions
on:
  workflow_dispatch:
  push:
    paths:
      -  definitions/**
      -  manifest.json
jobs:
  compile-bdbd:
    name: Build BDBD/JSON/XML definitions
    runs-on: ubuntu-latest
    steps:
    - name: Set tag name
      run: echo "NOW=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.NOW }}',
              sha: context.sha
          })
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Compile BDBD file with DBDefsConverter
      run: mkdir ${{ github.workspace }}/tmp && dotnet run --project ${{ github.workspace }}/code/C#/DBDefsConverter --configuration Release -- ${{ github.workspace }}/definitions ${{ github.workspace }}/tmp/all.bdbd bdbd
    - name: Compile JSON DBDs with DBDefsConverter
      run: dotnet run --project ${{ github.workspace }}/code/C#/DBDefsConverter --configuration Release -- ${{ github.workspace }}/definitions ${{ github.workspace }}/tmp/json json
    - name: Compile XML DBDs with DBDefsConverter
      run: dotnet run --project ${{ github.workspace }}/code/C#/DBDefsConverter --configuration Release -- ${{ github.workspace }}/definitions ${{ github.workspace }}/tmp/xml xml
    - name: Copy manifest
      run: cp ${{ github.workspace }}/manifest.json ${{ github.workspace }}/tmp/manifest.json
    - name: Archive DBDs
      uses: thedoctor0/zip-release@main
      with:
        directory: ${{ github.workspace }}/definitions
        type: 'zip'
        filename: ${{ github.workspace }}/tmp/dbd.zip
    - name: Archive JSONs
      uses: thedoctor0/zip-release@main
      with:
        directory: ${{ github.workspace }}/tmp/json
        type: 'zip'
        filename: ${{ github.workspace }}/tmp/json.zip
    - name: Archive XMLs
      uses: thedoctor0/zip-release@main
      with:
        directory: ${{ github.workspace }}/tmp/xml
        type: 'zip'
        filename: ${{ github.workspace }}/tmp/xml.zip
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v0.1.13
      with:
        name: Definitions v${{ env.NOW }}
        draft: false
        body: Current definitions at time of this release. Only DBD definitions are actively supported. While up-to-date, BDBD/JSON/XML definitions should be considered experimental.
        prerelease: false
        tag_name: ${{ env.NOW }}    
        files: |
            ${{ github.workspace }}/tmp/dbd.zip
            ${{ github.workspace }}/tmp/all.bdbd
            ${{ github.workspace }}/tmp/json.zip
            ${{ github.workspace }}/tmp/xml.zip
            ${{ github.workspace }}/tmp/manifest.json
